import fs from 'fs';


function init() {

    const rook_lines = gen_rook_lines()
    const bishop_lines = gen_bishop_lines()
    const blocker_fors = gen_blocker_fors()

    const data = `
% --- Auto generated by gen_geometry.js --- %

% --- rook lines ---
% rook_line(e4, e5).
% rook_line(e4, e6).
${rook_lines.map(([a, b]) => `rook_line(${a}, ${b}).`).join('\n')}

% --- bishop lines ---
% bishop_line(e4, f5).
${bishop_lines.map(([a, b]) => `bishop_line(${a}, ${b}).`).join('\n')}

% --- blockers ---
% blocker_for(e4, e7, e5).
% blocker_for(e4, e7, e6).
${blocker_fors.map(([a, b, c]) => `blocker_for(${a}, ${b}, ${c}).`).join('\n')}

`.trim()

    fs.writeFileSync('src/geometry.pl', data)
    console.log('written src/geometry.pl.')
}

let files = 'abcdefgh'
let ranks = '12345678'
const square_name = (i, j) => `${files[i]}${ranks[j]}`

const push_if_in_bounds = (aa, ai, aj, i, j) => {
    if (i >= 0 && i < 8 && j >= 0 && j < 8) {
        aa.push([square_name(ai, aj), square_name(i, j)])
    }
}

function gen_bishop_lines() {
    let res = []

    for (let i = 0; i < 8; i++) {
        for (let j = 0; j < 8; j++) {
            for (let step = 1; step < 8; step++) {
                push_if_in_bounds(res, i, j, i + step, j + step)
                push_if_in_bounds(res, i, j, i + step, j - step)
                push_if_in_bounds(res, i, j, i - step, j + step)
                push_if_in_bounds(res, i, j, i - step, j - step)
            }
        }
    }

    return res
}
function gen_rook_lines() {
    let res = []

    for (let i = 0; i < 8; i++) {
        for (let j = 0; j < 8; j++) {
            for (let step = 1; step < 8; step++) {
                push_if_in_bounds(res, i, j, i + step, j)
                push_if_in_bounds(res, i, j, i - step, j)
                push_if_in_bounds(res, i, j, i, j + step)
                push_if_in_bounds(res, i, j, i, j - step)
            }
        }
    }

    return res
}

function gen_blocker_fors() {
    let res = []

    const check_is_mid_line = (i, j, i2, j2, mi, mj) => {
        if (i > i2) {
            return false
        }
        if (j > j2) {
            return false
        }
        if (mi < i || mi > i2) {
            return false
        }
        if (mj < j || mj > j2) {
            return false
        }
        if ((mi === i && mj === j) || (mi === i2 && mj === j2)) {
            return false
        }
        for (let step = 1; step < 8; step++) {
            if (i + step === mi && j + step === mj) return true
            if (i + step === mi && j - step === mj) return true
            if (i - step === mi && j + step === mj) return true
            if (i - step === mi && j - step === mj) return true
            if (i === mi && j + step === mj) return true
            if (i === mi && j - step === mj) return true
            if (i + step === mi && j === mj) return true
            if (i - step === mi && j === mj) return true
        }
        return false
    }

    const push_if_in_mid = (aa, i, j, i2, j2, mi, mj) => {
        let if_in_mid = check_is_mid_line(i, j, i2, j2, mi, mj)
        if (if_in_mid) {
            aa.push([square_name(i, j), square_name(i2, j2), square_name(mi, mj)])
        }
    }

    for (let i = 0; i < 8; i++) {
        for (let j = 0; j < 8; j++) {

            for (let i2 = 0; i2 < 8; i2++) {
                for (let j2 = 0; j2 < 8; j2++) {

                    for (let mi = 0; mi < 8; mi++) {
                        for (let mj = 0; mj < 8; mj++) {
                            push_if_in_mid(res, i, j, i2, j2, mi, mj)
                        }
                    }

                }
            }
        }
    }



    return res
}

init()