import fs from 'fs';


function init() {


    const pawn_step = gen_pawn_step()

    const pawn_attack_geom = gen_pawn_attack_geom()
    const king_attack_geom = gen_king_attack_geom()
    const knight_attack_geom = gen_knight_attack_geom()

    const rook_lines = gen_rook_lines()
    const bishop_lines = gen_bishop_lines()
    const blocker_fors = gen_blocker_fors()

    const data = `
% --- Auto generated by gen_geometry.js --- %
:- module(geometry, [rook_line/2, bishop_line/2, blocker_for/3, pawn_attack_geom/3, king_attack_geom/2, knight_attack_geom/2, pawn_step/3]).

% --- rook lines ---
% rook_line(e4, e5).
% rook_line(e4, e6).
${rook_lines.map(([a, b]) => `rook_line(${a}, ${b}).`).join('\n')}

% --- bishop lines ---
% bishop_line(e4, f5).
${bishop_lines.map(([a, b]) => `bishop_line(${a}, ${b}).`).join('\n')}

% --- blockers ---
% blocker_for(e4, e7, e5).
% blocker_for(e4, e7, e6).
${blocker_fors.map(([a, b, c]) => `blocker_for(${a}, ${b}, ${c}).`).join('\n')}


% --- pawn attack geom ---
% pawn_attack_geom(white, e4, d5).
% pawn_attack_geom(white, e4, f5).
${pawn_attack_geom.map(([color, a, b]) => `pawn_attack_geom(${a}, ${b}, ${color}).`).join('\n')}

% --- king attack geom ---
% king_attack_geom(e4, e5).
% king_attack_geom(e4, f5).
% king_attack_geom(e4, f4).
${king_attack_geom.map(([a, b]) => `king_attack_geom(${a}, ${b}).`).join('\n')}


% --- knight attack geom ---
% knight_attack_geom(e4, f6).
% knight_attack_geom(e4, g5).
% knight_attack_geom(e4, g3).
% knight_attack_geom(e4, f2).
% knight_attack_geom(e4, d2).
% knight_attack_geom(e4, c3).
% knight_attack_geom(e4, c5).
% knight_attack_geom(e4, d6).
${knight_attack_geom.map(([a, b]) => `knight_attack_geom(${a}, ${b}).`).join('\n')}



% --- pawn step ---
% pawn_step(white, e2, e3).
% pawn_step(black, e7, e6).
${pawn_step.map(([color, a, b]) => `pawn_step(${a}, ${b}, ${color}).`).join('\n')}


`.trim()

    fs.writeFileSync('src/geometry.pl', data)
    console.log('written src/geometry.pl.')
}

let files = 'abcdefgh'
let ranks = '12345678'
const square_name = (i, j) => `${files[i]}${ranks[j]}`

const push_if_in_bounds = (aa, ai, aj, i, j) => {
    if (i >= 0 && i < 8 && j >= 0 && j < 8) {
        aa.push([square_name(ai, aj), square_name(i, j)])
    }
}

function gen_bishop_lines() {
    let res = []

    for (let i = 0; i < 8; i++) {
        for (let j = 0; j < 8; j++) {
            for (let step = 1; step < 8; step++) {
                push_if_in_bounds(res, i, j, i + step, j + step)
                push_if_in_bounds(res, i, j, i + step, j - step)
                push_if_in_bounds(res, i, j, i - step, j + step)
                push_if_in_bounds(res, i, j, i - step, j - step)
            }
        }
    }

    return res
}
function gen_rook_lines() {
    let res = []

    for (let i = 0; i < 8; i++) {
        for (let j = 0; j < 8; j++) {
            for (let step = 1; step < 8; step++) {
                push_if_in_bounds(res, i, j, i + step, j)
                push_if_in_bounds(res, i, j, i - step, j)
                push_if_in_bounds(res, i, j, i, j + step)
                push_if_in_bounds(res, i, j, i, j - step)
            }
        }
    }

    return res
}

function gen_blocker_fors() {
    let res = []

    const check_is_mid_line = (i, j, i2, j2, mi, mj) => {
        if ((mi === i && mj === j) || (mi === i2 && mj === j2)) {
            return false
        }

        const di = i2 - i
        const dj = j2 - j

        let stepI = 0
        let stepJ = 0

        if (di === 0 && dj !== 0) {
            // same row
            stepJ = Math.sign(dj)
        } else if (dj === 0 && di !== 0) {
            // same column
            stepI = Math.sign(di)
        } else if (Math.abs(di) === Math.abs(dj)) {
            // diagonal
            stepI = Math.sign(di)
            stepJ = Math.sign(dj)
        } else {
            // not collinear
            return false
        }

        let ci = i + stepI
        let cj = j + stepJ

        while (ci !== i2 || cj !== j2) {
            if (ci === mi && cj === mj) return true
            ci += stepI
            cj += stepJ
        }
        return false
    }

    const push_if_in_mid = (aa, i, j, i2, j2, mi, mj) => {
        let if_in_mid = check_is_mid_line(i, j, i2, j2, mi, mj)
        if (if_in_mid) {
            aa.push([square_name(i, j), square_name(i2, j2), square_name(mi, mj)])
        }
    }

    for (let i = 0; i < 8; i++) {
        for (let j = 0; j < 8; j++) {

            for (let i2 = 0; i2 < 8; i2++) {
                for (let j2 = 0; j2 < 8; j2++) {

                    for (let mi = 0; mi < 8; mi++) {
                        for (let mj = 0; mj < 8; mj++) {
                            push_if_in_mid(res, i, j, i2, j2, mi, mj)
                        }
                    }

                }
            }
        }
    }



    return res
}


function gen_king_attack_geom() {
    let res = []

    let step = 1
    for (let i = 0; i < 8; i++) {
        for (let j = 0; j < 8; j++) {
            push_if_in_bounds(res, i, j, i + step, j)
            push_if_in_bounds(res, i, j, i - step, j)
            push_if_in_bounds(res, i, j, i, j + step)
            push_if_in_bounds(res, i, j, i, j - step)
            push_if_in_bounds(res, i, j, i + step, j + step)
            push_if_in_bounds(res, i, j, i + step, j - step)
            push_if_in_bounds(res, i, j, i - step, j + step)
            push_if_in_bounds(res, i, j, i - step, j - step)
        }
    }
    return res
}

function gen_knight_attack_geom() {
    let res = []

    for (let i = 0; i < 8; i++) {
        for (let j = 0; j < 8; j++) {
            push_if_in_bounds(res, i, j, i + 2, j + 1)
            push_if_in_bounds(res, i, j, i - 2, j + 1)
            push_if_in_bounds(res, i, j, i + 1, j + 2)
            push_if_in_bounds(res, i, j, i + 1, j - 2)
            push_if_in_bounds(res, i, j, i - 1, j + 2)
            push_if_in_bounds(res, i, j, i - 1, j - 2)
            push_if_in_bounds(res, i, j, i + 2, j - 1)
            push_if_in_bounds(res, i, j, i - 2, j - 1)
        }
    }
    return res
}

function gen_pawn_attack_geom() {
    let res = []

    for (let i = 0; i < 8; i++) {
        for (let j = 1; j < 7; j++) {
            i < 8 && res.push(['white', square_name(i, j), square_name(i + 1, j + 1)])
            i > 0 && res.push(['white', square_name(i, j), square_name(i - 1, j + 1)])
            i < 8 && res.push(['black', square_name(i, j), square_name(i + 1, j - 1)])
            i > 0 && res.push(['black', square_name(i, j), square_name(i - 1, j - 1)])
        }
    }
    return res
}


function gen_pawn_step() {
    let res = []

    for (let i = 0; i < 8; i++) {
        for (let j = 1; j < 7; j++) {
            res.push(['white', square_name(i, j), square_name(i, j + 1)])
            res.push(['black', square_name(i, j), square_name(i, j - 1)])
        }
    }

    return res
}

init()