import fs from 'fs';
import { parseFen, makeFen } from 'chessops/fen';
import { square } from 'chessops/debug';
import { SquareSet, Chess, parseUci } from 'chessops';


function init() {

    let res = fs.readFileSync('data/test_b_forks_kr.log').toString()
    //let res = fs.readFileSync('data/test_single_out.csv').toString()

    let pieces = res.trim().split('\n').slice(0, 1000).map((_, i) => {
        let [id, fen, moves] = _.split(',')

        let uci = moves.split(' ')[0]
        let uci2 = moves.split(' ')[1]

        let move = parseUci(uci)

        let pos = Chess.fromSetup(parseFen(fen).unwrap()).unwrap()

        pos.play(move)

        let fen2 = makeFen(pos.toSetup())


        let pieces = []
        for (let sq of SquareSet.full()) {
            let p = pos.board.get(sq)
            if (p) {
                pieces.push([square(sq), p.color, p.role])
            }
        }


        //console.log(id, fen2, uci2)

        let from = uci2.slice(0, 2)
        let to = uci2.slice(2, 4)

        let turn = pos.turn

        let res = [`
% ${i} -- ${id} https://lichess.org/training/${id} ${fen2} ${uci2}
${pieces.map(([sq, color, role]) => `base_piece_at(id_${id}, ${sq}, ${color}, ${role}).`).join('\n')}
`,
        `base_side_to_move(id_${id}, ${turn}).`,

        `uci2(id_${id}, move(${from}, ${to})).`
        ]


        return res
    })

    let data = `
% --- Auto generated by gen_fens.js --- %
:- module(positions, [base_piece_at/4, base_side_to_move/2, uci2/2]).

${pieces.map(_ => _[0]).join('\n')}

${pieces.map(_ => _[1]).join('\n')}

${pieces.map(_ => _[2]).join('\n')}

    `

    
    fs.writeFileSync('src/positions.pl', data)
    console.log('written src/positions.pl.')
}


init()