
% --- Auto generated by gen_fens.js --- %
:- module(positions, [base_piece_at/4, base_side_to_move/2]).


% 0 -- 0ODMI https://lichess.org/training/0ODMI 6r1/pp2kp2/7R/2bpP3/7P/6B1/PP3PP1/2K5 b - - 0 27 g8g3
base_piece_at(id_0ODMI, c1, white, king).
base_piece_at(id_0ODMI, a2, white, pawn).
base_piece_at(id_0ODMI, b2, white, pawn).
base_piece_at(id_0ODMI, f2, white, pawn).
base_piece_at(id_0ODMI, g2, white, pawn).
base_piece_at(id_0ODMI, g3, white, bishop).
base_piece_at(id_0ODMI, h4, white, pawn).
base_piece_at(id_0ODMI, c5, black, bishop).
base_piece_at(id_0ODMI, d5, black, pawn).
base_piece_at(id_0ODMI, e5, white, pawn).
base_piece_at(id_0ODMI, h6, white, rook).
base_piece_at(id_0ODMI, a7, black, pawn).
base_piece_at(id_0ODMI, b7, black, pawn).
base_piece_at(id_0ODMI, e7, black, king).
base_piece_at(id_0ODMI, f7, black, pawn).
base_piece_at(id_0ODMI, g8, black, rook).
base_side_to_move(id_0ODMI, black).
 

    